# aurora-secret.yml (신규 생성)
apiVersion: v1
kind: Secret
metadata:
  name: user37-db-secret
  namespace: default
type: Opaque
data:
  # 아래의 값들은 본인의 실제 Aurora 정보 및 비밀키를 Base64 문자열로 변환하여 넣어야 합니다.
  # 명령어 예시: echo -n "admin" | base64
  SPRING_DATASOURCE_URL: user37-aurora-cluster.cluster-cqbgqrxkrfb4.us-east-1.rds.amazonaws.com

  SPRING_DATASOURCE_USERNAME: admin # admin의 base64 인코딩 값
  SPRING_DATASOURCE_PASSWORD: 12345678! # 데이터베이스 비밀번호의 base64 인코딩 값
  JWT_SECRET: aivle-bookapp-jwt-secret-key-2026! # 기존 jwt 시크릿키의 base64 인코딩 값
