apiVersion: apps/v1
kind: Deployment
metadata:
  name: user37-back-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: user37-backend
  template:
    metadata:
      labels:
        app: user37-backend
    spec:
      containers:
        - name: user37-backend
          image: <IMAGE_URI> # CodeBuild에서 자동 치환됨
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /books # 실제 동작하는 API 경로로 수정하세요
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user37-back-service
spec:
  type: ClusterIP # 내부 통신용으로만 개방
  selector:
    app: user37-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user37-back-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user37-back-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
